### ISSUE TITLE
Support for Full-Wiki (retrieval) Setting?

### ISSUE THREAD

**Issue by okhat** [Alab-NII/2wikimultihop#1]
Thanks for the exciting paper and dataset!

Is there support for a full-wiki / retrieval setting, besides the distractor setting?

I see that you (mostly) used a Wikipedia Jan 2020 dump. Are the answers restrictively collected from the abstracts like HotPotQA or from practically any passages on the relevant Wikipedia pages?

**Comment by xanhho** [comment]
Hi, thank you for your interest in the paper and dataset!

We do not support the full-wiki setting in the dataset.
Our focus in this dataset is to test the reasoning skills of the model on the fixed paragraphs.

For each Wikipedia page, we use the summary information of the page.
The summary information (also called short description) is the text between the title and the table "Contents" of the page.
I think in HotpotQA, they use the first paragraph in each Wikipedia page.

**Comment by okhat** [comment]
Thanks, @xanhho!

Do you think it should still be possible to use the questions and answers in an unofficial fullwiki setting? Any reason why that wouldn't work?

**Comment by xanhho** [comment]
I think it is possible to use the dataset in the full-wiki setting.
